#!/bin/bash

set -euo pipefail

echo "LIPI development loop"
echo ""
echo "Terminal 1: start the local stack"
echo "--------------------------------"
echo "docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d postgres valkey minio minio-init backend frontend"
echo ""
echo "Terminal 2: start the local control dashboard if needed"
echo "------------------------------------------------------"
echo "cd frontend-control"
echo "npm install"
echo "npm run dev -- --port 3001"
echo ""
echo "Terminal 3: start the hybrid tunnel if local backend needs remote ML/model"
echo "-------------------------------------------------------------------------"
echo "ssh -N -p 41447 \\"
echo "  -L 5001:localhost:5001 \\"
echo "  -L 8100:localhost:8210 \\"
echo "  -L 9000:localhost:9000 \\"
echo "  ekduiteen@202.51.2.50"
echo ""
echo "Important:"
echo "  - keep local :8000 for the local backend"
echo "  - do not tunnel remote :8000 onto local :8000 during local backend development"
echo "  - local :8100 is only a convenience port forwarded to remote :8210"
echo ""
echo "Verification:"
echo "  curl http://127.0.0.1:8000/health"
echo "  curl http://127.0.0.1:5001/health"
echo "  curl http://127.0.0.1:8100/v1/models"
echo "  curl -I http://127.0.0.1:3000"
echo "  curl -I http://127.0.0.1:3001"
echo ""
echo "Deploy rule:"
echo "  - commit backend changes first"
echo "  - sync committed source to /data/lipi"
echo "  - rebuild remote backend"
